server:
 port: 8081
 servlet:
  context-path: /resource-server

spring:
 h2:
  console:
   enable: true
   path: /h2-ui
  datasource:
   url: jdbc:h2:mem:testdb
   driverClassName: org.h2.Driver
#   username: admin
#   password: P@$$w0rd
  jpa:
   database-platform: org.hibernate.dialect.H2Dialect
   
#   show-sql: true
#    properties:
#     hibernate:
#      dialect: org.hibernate.dialect.H2Dialect
#      ddl-auto: update

# JWT CONFIGURATION
perspro:
 app:
  jwtCookieName: perspro
  jwtSecret: persproJwtSecretKey
  jwtExpirationMs: 86400000
#      jwtRefreshCookieName: perspro-jwt-refresh
#      jwtRefreshExpirationMs: 86400000
  
# For test
#perspro:
# app:
#  jwtExpirationMs: 60000
#  jwtRefreshExpirationMs: 180000


